spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM551405
spring.datasource.password=fiapxih7!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=false

server.port=80